service: xray-monitor

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
        - "xray:*"
       Resource:
        - "*"

plugins:
  - serverless-plugin-typescript

functions:
  report:
    handler: src/handler.reportExceptions
    events:
      - schedule: rate(5 minutes)
    memorySize: 128
    environment:
      SLACK_TOKEN: PASTE_YOUR_SLACK_TOKEN_HERE
      SLACK_CHANNEL: PASTE_SLACK_CHANNEL_ID_HERE
